# Generated by Django 5.2.13 on 2026-08-03 18:37

import baserow.core.formula.field
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arabase", "0001_chart_widget_and_grouped_aggregation"),
        ("core", "0116_jadawel_arabic_english_only"),
        ("dashboard", "0003_widget_dashboarddatasource_summarywidget"),
        ("database", "0210_jadawel_rename_default_grid_views"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalBaserowUpcomingRows",
            fields=[
                (
                    "service_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.service",
                    ),
                ),
                (
                    "search_query",
                    baserow.core.formula.field.FormulaField(
                        blank=True,
                        default="",
                        help_text="The query to apply to the service to narrow the results down.",
                        null=True,
                    ),
                ),
                (
                    "filter_type",
                    models.CharField(
                        choices=[("AND", "And"), ("OR", "Or")],
                        default="AND",
                        help_text="Indicates whether all the rows should apply to all filters (AND) or to any filter (OR).",
                        max_length=3,
                    ),
                ),
                (
                    "default_result_count",
                    models.PositiveIntegerField(
                        db_default=10,
                        default=10,
                        help_text="The number of records returned with each page.",
                    ),
                ),
                (
                    "days_ahead",
                    models.PositiveIntegerField(
                        db_default=7,
                        default=7,
                        help_text="How many days ahead of today to include.",
                    ),
                ),
                (
                    "include_overdue",
                    models.BooleanField(
                        db_default=True,
                        default=True,
                        help_text="Whether records whose date has already passed are included.",
                    ),
                ),
                (
                    "date_field",
                    models.ForeignKey(
                        help_text="The date field defining when a record is due.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.field",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.table",
                    ),
                ),
                (
                    "view",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.view",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.service", models.Model),
        ),
        migrations.CreateModel(
            name="ProgressWidget",
            fields=[
                (
                    "widget_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dashboard.widget",
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        db_default=100,
                        decimal_places=10,
                        default=100,
                        help_text="The value that counts as 100%.",
                        max_digits=50,
                    ),
                ),
                (
                    "display_style",
                    models.CharField(
                        choices=[("bar", "Bar"), ("ring", "Ring")],
                        db_default="bar",
                        default="bar",
                        help_text="Whether progress is drawn as a bar or a ring.",
                        max_length=8,
                    ),
                ),
                (
                    "warning_threshold",
                    models.PositiveIntegerField(
                        db_default=50,
                        default=50,
                        help_text="Percentage at or above which progress is no longer at risk.",
                    ),
                ),
                (
                    "success_threshold",
                    models.PositiveIntegerField(
                        db_default=100,
                        default=100,
                        help_text="Percentage at or above which progress counts as met.",
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        help_text="The aggregation this widget measures.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dashboard.dashboarddatasource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("dashboard.widget",),
        ),
        migrations.CreateModel(
            name="RecordsListWidget",
            fields=[
                (
                    "widget_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dashboard.widget",
                    ),
                ),
                (
                    "field_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ids of the fields to show, in order. Empty means the widget picks the first few fields of the table itself.",
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        help_text="The rows this widget lists.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dashboard.dashboarddatasource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("dashboard.widget",),
        ),
        migrations.CreateModel(
            name="UpcomingDatesWidget",
            fields=[
                (
                    "widget_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dashboard.widget",
                    ),
                ),
                (
                    "field_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ids of the fields to show alongside the date, in order.",
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        help_text="The upcoming rows this widget lists.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dashboard.dashboarddatasource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("dashboard.widget",),
        ),
    ]
