# Generated by Django 5.2.13 on 2026-08-08 22:48

import secrets

import django.db.models.deletion
from django.db import migrations, models

import jadawel.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("arabase", "0003_jadawel_rename_local_jadawel_models"),
        ("dashboard", "0004_widget_width_height"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardShare",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", jadawel.core.fields.SyncedDateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        default=secrets.token_urlsafe,
                        help_text="The unique slug where the dashboard can be accessed publicly on.",
                        unique=True,
                    ),
                ),
                (
                    "public_view_password",
                    models.CharField(
                        blank=True,
                        help_text="The password required to access the public dashboard URL.",
                        max_length=128,
                    ),
                ),
                (
                    "dashboard",
                    models.OneToOneField(
                        help_text="The dashboard that is shared through this link.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share",
                        to="dashboard.dashboard",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
