# Generated by Django 5.2.13 on 2026-08-15 17:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabase', '0004_dashboard_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_on', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=16)),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual')], default='scheduled', max_length=16)),
                ('key', models.TextField(blank=True, default='', help_text='Object key of the database dump.')),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('media_key', models.TextField(blank=True, default='', help_text='Object key of the user-file archive.')),
                ('media_size_bytes', models.BigIntegerField(default=0)),
                ('pruned_count', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='', help_text='Why the run failed. Empty on a successful run.')),
            ],
            options={
                'ordering': ('-started_on', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', help_text='How often a backup is taken.', max_length=16)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'backup schedule',
            },
        ),
    ]
