# Generated by Django 5.2.13 on 2026-08-16 08:42

import django.db.models.deletion
import jadawel.core.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabase', '0005_backuprun_backupschedule'),
        ('database', '0211_jadawel_rename_table_usage_functions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlPageView',
            fields=[
                ('view_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.view')),
                ('html', models.TextField(blank=True, help_text='The HTML document that is rendered for this view.')),
                ('allow_external_resources', models.BooleanField(db_default=False, default=False, help_text='When true the page may load scripts, styles and fonts from the configured CDN allowlist. Network requests from the page stay blocked either way.')),
                ('row_limit', models.PositiveIntegerField(db_default=200, default=200, help_text='How many rows are handed to the page when it renders.')),
            ],
            options={
                'abstract': False,
            },
            bases=('database.view',),
        ),
        migrations.CreateModel(
            name='HtmlPageViewFieldOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False, help_text="Whether the field is withheld from the page's data feed.")),
                ('order', models.SmallIntegerField(default=32767, help_text="The order the field has in the page's data feed. Lower is first.")),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.field')),
                ('html_page_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arabase.htmlpageview')),
            ],
            options={
                'ordering': ('order', 'field_id'),
                'unique_together': {('html_page_view', 'field')},
            },
        ),
        migrations.AddField(
            model_name='htmlpageview',
            name='field_options',
            field=models.ManyToManyField(through='arabase.HtmlPageViewFieldOptions', to='database.field'),
        ),
        migrations.CreateModel(
            name='HtmlPageViewRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', jadawel.core.fields.SyncedDateTimeField(auto_now=True)),
                ('html', models.TextField(blank=True, help_text='The HTML this page had before the change that created this row.')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who replaced this version, if they still exist.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('html_page_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='arabase.htmlpageview')),
            ],
            options={
                'ordering': ('-created_on', '-id'),
            },
        ),
    ]
