# Generated by Django 5.2.7 on 2026-08-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import jadawel.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("arabase", "0007_mcp_protection_policy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MCPProtectionCommand",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_on",
                    jadawel.core.fields.SyncedDateTimeField(auto_now=True),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("request_fingerprint", models.CharField(max_length=64)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_protection_commands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "endpoint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arabase_creation_command",
                        to="core.mcpendpoint",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["actor", "created_on"],
                        name="ara_mcp_cmd_actor_created_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("actor", "idempotency_key"),
                        name="arabase_unique_mcp_command_key",
                    )
                ],
            },
        )
    ]
