# Generated by Django 5.2.13 on 2026-08-30 17:22

import django.db.models.deletion
import jadawel.core.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabase', '0012_mcp_protection_audit_binding'),
        ('core', '0117_jadawel_rename_show_help_request'),
        ('database', '0211_jadawel_rename_table_usage_functions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', jadawel.core.fields.SyncedDateTimeField(auto_now=True)),
                ('content_digest', models.CharField(max_length=64)),
                ('configuration_fingerprint', models.CharField(max_length=64)),
                ('manifest_fingerprint', models.CharField(max_length=64)),
                ('policy_revision', models.PositiveBigIntegerField()),
                ('access_generation', models.PositiveBigIntegerField()),
                ('target_generation', models.PositiveBigIntegerField()),
                ('audience', models.CharField(choices=[('authenticated', 'Authenticated viewers'), ('public', 'Public viewers')], max_length=16)),
                ('audience_fingerprint', models.CharField(max_length=64)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, default='', max_length=64)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_artifact_approvals_granted', to=settings.AUTH_USER_MODEL)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_artifact_approvals', to='core.mcpendpoint')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_artifact_approvals', to='arabase.htmlpageview')),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', jadawel.core.fields.SyncedDateTimeField(auto_now=True)),
                ('candidate_html', models.TextField(blank=True)),
                ('content_digest', models.CharField(max_length=64)),
                ('configuration_fingerprint', models.CharField(max_length=64)),
                ('manifest_fingerprint', models.CharField(max_length=64)),
                ('requested_field_ids', models.JSONField(default=list)),
                ('pending_view_values', models.JSONField(default=dict)),
                ('audience', models.CharField(choices=[('authenticated', 'Authenticated viewers'), ('public', 'Public viewers')], default='authenticated', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('superseded', 'Superseded'), ('revoked', 'Revoked')], default='pending', max_length=16)),
                ('nonce', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_artifact_drafts', to='core.mcpendpoint')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_artifact_drafts_submitted', to=settings.AUTH_USER_MODEL)),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_artifact_drafts', to='arabase.htmlpageview')),
            ],
            options={
                'ordering': ('-created_on', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ArtifactAuditEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', jadawel.core.fields.SyncedDateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=32)),
                ('audience', models.CharField(blank=True, default='', max_length=16)),
                ('metadata', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_artifact_audit_events', to=settings.AUTH_USER_MODEL)),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='arabase.artifactapproval')),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_artifact_audit_events', to='core.mcpendpoint')),
                ('view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_artifact_audit_events', to='arabase.htmlpageview')),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='arabase.artifactdraft')),
            ],
        ),
        migrations.AddField(
            model_name='artifactapproval',
            name='draft',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='arabase.artifactdraft'),
        ),
        migrations.CreateModel(
            name='ArtifactManifestField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', jadawel.core.fields.SyncedDateTimeField(auto_now=True)),
                ('stable_field_id', models.PositiveBigIntegerField()),
                ('field_name_snapshot', models.CharField(max_length=255)),
                ('table_id_snapshot', models.PositiveBigIntegerField()),
                ('provenance', models.CharField(choices=[('direct', 'Direct protected field'), ('derived', 'Derived protected field')], max_length=16)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifest_fields', to='arabase.artifactdraft')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_artifact_manifest_fields', to='database.field')),
            ],
        ),
        migrations.CreateModel(
            name='HtmlPageArtifactState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', jadawel.core.fields.SyncedDateTimeField(auto_now=True)),
                ('target_generation', models.PositiveBigIntegerField(default=1)),
                ('public_only', models.BooleanField(default=False)),
                ('active_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_states', to='arabase.artifactapproval')),
                ('view', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_artifact_state', to='arabase.htmlpageview')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='artifactdraft',
            index=models.Index(fields=['endpoint', 'view', 'status'], name='ara_art_draft_ep_view_idx'),
        ),
        migrations.AddIndex(
            model_name='artifactdraft',
            index=models.Index(fields=['view', 'created_on'], name='ara_art_draft_view_created_idx'),
        ),
        migrations.AddIndex(
            model_name='artifactauditevent',
            index=models.Index(fields=['view', 'created_on'], name='ara_art_audit_view_created_idx'),
        ),
        migrations.AddIndex(
            model_name='artifactapproval',
            index=models.Index(fields=['view', 'audience', 'revoked_at'], name='ara_art_ap_view_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='artifactapproval',
            index=models.Index(fields=['endpoint', 'policy_revision'], name='ara_art_ap_ep_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='artifactmanifestfield',
            index=models.Index(fields=['stable_field_id', 'provenance'], name='ara_art_manifest_field_idx'),
        ),
        migrations.AddConstraint(
            model_name='artifactmanifestfield',
            constraint=models.UniqueConstraint(fields=('draft', 'stable_field_id'), name='ara_art_manifest_draft_field_unique'),
        ),
    ]
