# Generated by Django 5.2.13 on 2026-08-30 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabase', '0013_artifactapproval_artifactdraft_artifactauditevent_and_more'),
        ('core', '0117_jadawel_rename_show_help_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlpageartifactstate',
            name='endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_artifact_states', to='core.mcpendpoint'),
        ),
    ]
