# Generated by Django 5.2.13 on 2026-08-06 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_jadawel_rename_show_help_request'),
        ('database', '0211_jadawel_rename_table_usage_functions'),
        ('integrations', '0028_jadawel_rename_local_jadawel_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localjadaweltableservicefieldmapping',
            name='service',
            field=models.ForeignKey(help_text='The LocalJadawel Service that this field mapping relates to.', on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='core.service'),
        ),
        migrations.AlterField(
            model_name='localjadaweltableservicefilter',
            name='field',
            field=models.ForeignKey(help_text='The database Field, in the LocalJadawelTableService, which we would like to filter upon.', on_delete=django.db.models.deletion.CASCADE, to='database.field'),
        ),
        migrations.AlterField(
            model_name='localjadaweltableservicesort',
            name='field',
            field=models.ForeignKey(help_text='The database Field, in the LocalJadawelTableService service, which we would like to sort upon.', on_delete=django.db.models.deletion.CASCADE, to='database.field'),
        ),
    ]
